# Generated by Django 4.1.3 on 2022-11-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('id', models.CharField(db_column='ID', max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(db_column='PW', max_length=20)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyRoutin',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='support.members')),
                ('recent_meal', models.DateTimeField(blank=True, null=True)),
                ('recent_exercise', models.DateTimeField(blank=True, null=True)),
                ('recent_clean', models.DateTimeField(blank=True, null=True)),
                ('goal_meal', models.IntegerField(blank=True, null=True)),
                ('goal_exercise', models.IntegerField(blank=True, null=True)),
                ('goal_clean', models.IntegerField(blank=True, null=True)),
                ('today_meal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_routin',
                'managed': False,
            },
        ),
    ]
