# Generated by Django 4.1.3 on 2022-11-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_id',
            field=models.OneToOneField(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user'),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_id',
            field=models.OneToOneField(db_column='recent_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user'),
        ),
    ]
