# Generated by Django 4.1.3 on 2022-11-30 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recent_meal_count_alter_recent_recent_clean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('home_id', models.OneToOneField(db_column='home_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('air_conditioner', models.BooleanField(default=0)),
                ('air_puritier', models.BooleanField(default=0)),
                ('tv', models.BooleanField(default=0)),
                ('robot_clean', models.BooleanField(default=0)),
                ('air_conditioner_name', models.CharField(max_length=30)),
                ('air_puritier_name', models.CharField(max_length=30)),
                ('tv_name', models.CharField(max_length=30)),
                ('robot_clean_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'homeaplliance',
            },
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_clean',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 20, 8, 7, 873835)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_exercise',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 20, 8, 7, 873835)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_meal',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 20, 8, 7, 873835)),
        ),
    ]
