# Generated by Django 4.1.3 on 2022-12-02 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homeconnection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnOn',
            fields=[
                ('turnon_id', models.OneToOneField(db_column='home_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('air_conditioner', models.BooleanField(default=0)),
                ('air_purifier', models.BooleanField(default=0)),
                ('tv', models.BooleanField(default=0)),
                ('robot_clean', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'turnon',
            },
        ),
        migrations.RenameModel(
            old_name='HomeAppliance',
            new_name='HomeConnect',
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_clean',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 11, 23, 4, 305391)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_exercise',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 11, 23, 4, 305391)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_meal',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 11, 23, 4, 305391)),
        ),
        migrations.AlterModelTable(
            name='homeconnect',
            table='homeconnect',
        ),
        migrations.DeleteModel(
            name='HomeConnection',
        ),
    ]
