# Generated by Django 4.1.3 on 2022-11-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('pw', models.CharField(max_length=30)),
                ('location1', models.CharField(blank=True, max_length=10)),
                ('location2', models.CharField(max_length=10)),
                ('location3', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_meal', models.DateTimeField()),
                ('meal_count', models.IntegerField()),
                ('recent_exercise', models.DateTimeField()),
                ('recent_clean', models.DateTimeField()),
                ('recent_id', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'recent',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('clean', models.IntegerField()),
                ('goal_id', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'goal',
            },
        ),
    ]
