# Generated by Django 4.1.3 on 2022-11-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=30)),
                ('location', models.CharField(default='서울시 성동구', max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('meal', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('clean', models.IntegerField()),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('recent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('recent_meal', models.DateTimeField()),
                ('meal_count', models.IntegerField()),
                ('recent_exercise', models.DateTimeField()),
                ('recent_clean', models.DateTimeField()),
            ],
            options={
                'db_table': 'recent',
            },
        ),
    ]
