# Generated by Django 4.1.3 on 2022-11-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location3',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='서울시 성동구', max_length=30),
        ),
    ]
