# Generated by Django 4.1.3 on 2022-11-29 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goal_goal_id_alter_recent_recent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='meal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_clean',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 4, 7, 13, 947165)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_exercise',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 4, 7, 13, 947165)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_meal',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 4, 7, 13, 947165)),
        ),
    ]
