# Generated by Django 4.1.3 on 2022-11-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.CharField(help_text='User ID', max_length=20, primary_key=True, serialize=False)),
                ('pswd', models.CharField(help_text='User Password', max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stretching', models.BooleanField(default=False, help_text='Like=True')),
                ('home_training', models.BooleanField(default=False, help_text='Like=True')),
                ('dance', models.BooleanField(default=False, help_text='Like=True')),
                ('yoga', models.BooleanField(default=False, help_text='Like=True')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='my_api.members')),
            ],
        ),
    ]
